server:
  port: 8080

spring:
  application:
    name: localizador-pets

positionstack:
  api:
    url: https://api.positionstack.com/v1
    key: ${POSITIONSTACK_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.itau.localizador_pets: DEBUG

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /api-docs


