server:
  port: 8080

spring:
  application:
    name: localizador-pets

info:
  app:
    name: Localizador de Pets
    description: API para localização de pets via PositionStack
    version: 1.0.0

positionstack:
  api:
    url: https://api.positionstack.com/v1
    key: ${POSITIONSTACK_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, httpexchanges
  endpoint:
    health:
      show-details: always
    httpexchanges:
      enabled: true
  info:
    env:
      enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.itau.localizador_pets: DEBUG

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /api-docs




